### ISSUE TITLE
Cannot disable xdist when sugar is installed

### ISSUE THREAD

**Issue by azmeuk** [Frozenball/pytest-sugar#124]
This bug report was originally posted at [pytest-xdist's](https://github.com/pytest-dev/pytest-xdist/issues/147) but it seems the fault is actually on sugar :) There may be some clues in this bug report though.

#### Command used to run py.test
````bash
pip install pytest pytest-xdist pytest-sugar
pytest -p no:xdist test_foobar.py
````

#### Test file
````python
def test_false(): assert False
````

#### Output
````
Test session starts (platform: linux, Python 3.6.1, pytest 3.1.0, pytest-sugar 0.8.0)
rootdir: /home/eloi/pytest-xdist-test, inifile:
plugins: xdist-1.16.0, sugar-0.8.0
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/main.py", line 105, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/main.py", line 140, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/main.py", line 150, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/main.py", line 605, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/home/eloi/pytest-xdist-test/env/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 498, in check_pending
INTERNALERROR>     (name, hookimpl.plugin))
INTERNALERROR> _pytest.vendored_packages.pluggy.PluginValidationError: unknown hook 'pytest_xdist_node_collection_finished' in plugin <module 'pytest_sugar' (<_pytest.assertion.rewrite.AssertionRewritingHook object at 0x7f45f9176358>)>
````
Thank you

**Comment by RonnyPfannschmidt** [comment]
the clue is in https://github.com/Frozenball/pytest-sugar/blob/master/pytest_sugar.py#L82

that check adds a hook when xdist is installed, even when it it disabled
in order to
https://docs.pytest.org/en/latest/writing_plugins.html#optionally-using-hooks-from-3rd-party-plugins shows a good way to add the hook only when xdist is enabled

**Comment by drcongo** [comment]
I installed, and then removed pytest-xdist and now can't use pytest-sugar for some reason. Well, I can if I comment out the check for it. 

    pip uninstall pytest-xdist
    Cannot uninstall requirement pytest-xdist, not installed

However, `import xdist` doesn't fail any more and I can't work out why.

**Comment by Frozenball** [comment]
@drcongo I am not sure what is the problem here?

**Comment by Frozenball** [comment]
@azmeuk What's the use case for disabling xdist? Does this bug have real impact or is it just nice to have?

@RonnyPfannschmidt It's getting a bit embarrassing how many pytest-sugar bugs seem to leak into other repositories... 😰

**Comment by RonnyPfannschmidt** [comment]
@Frozenball i wouldnt consider it a bug - its more if a really messy detail thats too easily missed

**Comment by azmeuk** [comment]
@Frozenball Using xdist is nice when you have a lot of tests to run, but the initialization phase can be long. When I have a single, or a small set of tests to run, and I know the initialization takes more time than what I gained from the parallelization, I generally disable pytest-xdist.

Also sometime pytest-xdist has its own bugs and needs to be disabled.

**Comment by RonnyPfannschmidt** [comment]
@azmeuk also note that xdist only triggers if you request it, so disabling the whole plugin in general doesnt make sense as you only have to avoid requesting the parallel execution

**Comment by Frozenball** [comment]
Yeah, isn't omitting `-n` (the parallel factor) enough?

**Comment by standage** [comment]
> I installed, and then removed pytest-xdist and now can't use pytest-sugar for some reason.

Same here. I thought pytest-xdist might speed up my test build, but it didn't help much and even slowed down some parts. But after running `pip uninstall -y pytest-xdist` now pytest-sugar doesn't work.

```
File "/Users/standage/anaconda3/envs/kevlar/lib/python3.6/site-packages/pytest_sugar.py", line 87, in <module>
    xdist_version = LooseVersion(xdist.__version__)
AttributeError: module 'xdist' has no attribute '__version__'
```

> However, `import xdist` doesn't fail any more and I can't work out why.

It looks like `pip uninstall -y pytest-xdist` leaves the `site-packages/xdist/` directory behind. Manually removing this directory makes sure that `import xdist` fails and triggers the correct pytest-sugar behavior.

**Comment by blueyed** [comment]
Should work also through the method @RonnyPfannschmidt pointed out: https://github.com/Frozenball/pytest-sugar/pull/147.

**Comment by blueyed** [comment]
@standage 
It should also fix your issue, but maybe another fix on top would make sense.  Please consider filing a separate issue and/or opening a PR then.

**Comment by blueyed** [comment]
Would be good if you could test that https://github.com/Frozenball/pytest-sugar/pull/147 works for you.

**Comment by marscher** [comment]
#147 works for me.
