### ISSUE TITLE
xdist options generate different results

### ISSUE THREAD

**Issue by aljosa** [Frozenball/pytest-sugar#52]
"py.test -f tests/" on left vs. "py.test tests/" on right:
can't figure out why results are different so i'm guessing it's an issue?

![sugar-xdist-issue](https://cloud.githubusercontent.com/assets/31008/5319614/1b08e070-7cab-11e4-9618-4190fb2d9b6c.png)

**Comment by Frozenball** [comment]
This has been fixed.
