### ISSUE TITLE
--nosugar does not completely disable sugar

### ISSUE THREAD

**Issue by icemac** [Frozenball/pytest-sugar#61]
When running the tests in Jenkins with the --nosugar option it displays the escape sequences to render the test passes or failures in color. This is not the case if pytest-sugar ist not installed.

**Comment by Frozenball** [comment]
Thanks for letting me know.

**Comment by RonnyPfannschmidt** [comment]
shoulnt -p no:sugar fix it as well?

**Comment by Frozenball** [comment]
Shouldnt we just get rid of the --nosugar and replace it with -p no:sugar?

**Comment by icemac** [comment]
+1 to remove `--nosugar` but documenting `-p no:sugar`.
I learned this option from the  comments in this ticket and it works like a charm. (Thanks @RonnyPfannschmidt )

**Comment by Frozenball** [comment]
This option was deprecated with version 0.5.0.
