### ISSUE TITLE
xfail test is not reported as such if parametrized

### ISSUE THREAD

**Issue by matclab** [Frozenball/pytest-sugar#68]
```python
    @pytest.mark.xfail(reason="Not implemented")
    @pytest.mark.parametrize('controller', ['found'])
    def inactivated_objects_should_not_be_found(w)
```
doesn't appear in the results (neither with an 'x', neither in the summary as xfailed). 
But the following test does:

```python
    @pytest.mark.xfail(reason="Not implemented")
    def inactivated_objects_should_not_be_found(w)
```

**Comment by RonnyPfannschmidt** [comment]
does this happen with plain pytest as well?

**Comment by matclab** [comment]
No, I noticed this when I ran `py.test -p no:sugar` and then I got 3 xfailed test, whereas I got only 2 xfailed test reported with sugar.

I also use a bunch of other plugins:
```
splinter, hypothesis-pytest, sugar, mock, describe, robpol86-pytest-ipdb, catchlog, stepwise, cache
```
Tell me if you're not able to reproduce. I can investigate a bit more with some directions on where to look.

**Comment by RonnyPfannschmidt** [comment]
im not working on pytest-sugar myself, i just wanted to see if it was related to pytest itself

**Comment by Frozenball** [comment]
This doesn't seem to happen anymore.
