### ISSUE TITLE
tests skipped with pytest.mark.skipif not shown at all

### ISSUE THREAD

**Issue by patrickdepinguin** [Frozenball/pytest-sugar#75]
If I use pytest.mark.skipif for a test, the test is not shown as
'skipped' with pytest-sugar, while regular pytest does.
If I use nose.plugins.skip.SkipTest from a test instead, pytest-sugar
_does_ see it as skipped.

Example code is the following:

    import pytest
    import nose

    def test_foo():
        assert True

    @pytest.mark.skipif(True, reason='testing skipping')
    def test_skipped():
        assert False

    def test_nose_skipped():
        raise nose.plugins.skip.SkipTest('nose skipping')
        assert False

I tried to add some debug statements in pytest_sugar.py, and noticed
that for the skipif test there is a 'setup' trigger where
report.status says 'skipped' but it becomes 'passed' in the 'teardown'
trigger. There is no 'call' trigger for that skipped test.
I have not been able to determine any useful things further.

This is reported against pytest-sugar 0.5.1 and pytest 2.8.7.
I verified that the same problem is present with older versions of pytest-sugar, so it seems this never worked.

**Comment by patrickdepinguin** [comment]
ping?

**Comment by Frozenball** [comment]
I can confirm this issue.

**Comment by patrickdepinguin** [comment]
Fix confirmed, thanks. Will a new release be created so the updated version is available from PyPi and installable via pip ? Thanks!

**Comment by Frozenball** [comment]
0.7.0 was just released.
