### ISSUE TITLE
Result summary counts exception in fixture as failure

### ISSUE THREAD

**Issue by icemac** [Frozenball/pytest-sugar#94]
Running the tests without pytest-sugar counts an exception in the fixture as error while running with pytest-sugar the same exception is counted as a failure.

Example without py-test:

```
$ bin/py.test -k test___getattr___looks_up_key_in_metadata -p no:sugar
=========================== test session starts ===========================
platform darwin -- Python 2.7.11, pytest-2.9.0, py-1.4.30, pluggy-0.3.1
rootdir: /Users/..., inifile: pytest.ini
plugins: gocept.pytestlayer-2.1, cov-1.8.1, rerunfailures-0.5, remove-stale-bytecode-1.0
collected 494 items

xxx/test_article.py EE

[…]
================= 493 deselected, 2 error in 8.55 seconds =======================
```

Same example with pytest-sugar:

```
$ bin/py.test -k test___getattr___looks_up_key_in_metadata
Test session starts (platform: darwin, Python 2.7.11, pytest 2.9.0, pytest-sugar 0.7.1)
rootdir: /Users/..., inifile: pytest.ini
plugins: gocept.pytestlayer-2.1, cov-1.8.1, rerunfailures-0.5, remove-stale-bytecode-1.0, sugar-0.7.1

[…]
======== 493 tests deselected by '-ktest___getattr___looks_up_key_in_metadata' =========

Results (6.26s):
         2 failed
         - /Users/.../testing.py:74: RuntimeError: ...
         - /Users/.../Connection.py:248: AttributeError: ...
     493 deselected
```

Expectation: Exceptions during the setup of the test should be counted as errors as py.test does it.
What is the reason not to do so in pytest-sugar?

**Comment by blueyed** [comment]
@icemac 
Have you investigated what the reason might be by chance?  Just noticed this myself.

**Comment by blueyed** [comment]
With pytest-sugar, `terminalreporter.stats` in another plugin's pytest_terminal_summary has:


 'failed': [<TestReport 'test_foo.py::test_1' when='call' outcome='failed'>,
            <TestReport 'test_foo.py::test_2' when='setup' outcome='failed'>],
 'passed': [<TestReport 'test_foo.py::test_1' when='setup' outcome='passed'>,
            <TestReport 'test_foo.py::test_1' when='teardown' outcome='passed'>,
            <TestReport 'test_foo.py::test_2' when='teardown' outcome='passed'>]}

And with `-p no:sugar`:

{'': [<TestReport 'velodrome/lock8/tests/test_metrics.py::test_1' when='setup' outcome='passed'>,
      <TestReport 'velodrome/lock8/tests/test_metrics.py::test_1' when='teardown' outcome='passed'>,
      <TestReport 'velodrome/lock8/tests/test_metrics.py::test_2' when='teardown' outcome='passed'>],
 'error': [<TestReport 'velodrome/lock8/tests/test_metrics.py::test_2' when='setup' outcome='failed'>],
 'failed': [<TestReport 'velodrome/lock8/tests/test_metrics.py::test_1' when='call' outcome='failed'>]}

So pytest-sugar also appears to move entries from `''` to `'passed'`.

**Comment by Frozenball** [comment]
Fixed
