### ISSUE TITLE
Pass/fail summary not viewable when using xdist

### ISSUE THREAD

**Issue by westhomas** [Frozenball/pytest-sugar#99]
I'm using pytest-xdist to run tests in parallel. The summary output at the end of a test run is much longer when using xdist than when running tests normally. The output is being truncated such that I can't read the failure messages. 

Normal output without xdist:

```
       1 failed
         - /code/summit/summit/test/base.py:223: AssertionError: '12' != ''
```

Output when running with xdist:

```
       1 failed
         - self = <summit.test.simple.SimpleFunctionalTest te
```

Is there someway to increase this value in settings?

**Comment by Frozenball** [comment]
So it seems like xdist changes the output of `self._getcrashline`.

With xdist:
<img width="345" alt="screen shot 2016-12-25 at 20 37 07" src="https://cloud.githubusercontent.com/assets/53298/21472432/ff006fec-cae1-11e6-8150-6ab8160a2354.png">

Without:
<img width="805" alt="screen shot 2016-12-25 at 20 37 52" src="https://cloud.githubusercontent.com/assets/53298/21472433/06d90d0a-cae2-11e6-9d60-94b8a86c46b9.png">

This is the code at pytest:
````
    def _getcrashline(self, rep):
        try:
            return str(rep.longrepr.reprcrash)
        except AttributeError:
            try:
                return str(rep.longrepr)[:50]
            except AttributeError:
                return ""
````

so it seems like `rep.longrepr.reprcrash` is not available.

As a workaround, you can use `--new-summary` that uses different method for getting the summary.
